Schema representation improvements
Authress-Engineering/openapi-explorer pull request #253
Opened 2024-05-24 13:24 UTC by zlondrej

I made some changes to the way schemas are visualized to better fit my use cases, but I think they're more general use cases and are in-line with what OpenAPI is describing.

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5196749/077ba078-bb71-4218-b92b-826ca3eae9ee)

I also added new `schema-compact-single-x-of-option` option for more compact display of single item `xxxOf`. It would be better to move the schema link to the type column, but internal representation is a too messy for that and I can't spend that much extra time on it, as that would require substantial rewrite.

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5196749/3dd91670-e77a-4bd6-a998-ea963262f9fb)

Additional details can be found in the documentation and changelog.

2024-05-24 13:58 UTC, wparad commented
I'm concerned that there is just too much going on in this PR in order to test, validate, and review it effectively. Can you split this and start with just the smallest one change you consider to be most important, and then we can work on it from there?

Right now I have too many questions and the individuals discussions are going to get conflated as we try to discuss each one.

2024-05-24 13:59 UTC, wparad requested changes
Re comment, please split.

2024-05-24 14:49 UTC, zlondrej commented
Well, I was expecting this a bit but it was worth a try. I will try to split them once I have some more time to spare on this.

2024-05-24 15:01 UTC, wparad commented
> Well, I was expecting this a bit but it was worth a try. I will try to split them once I have some more time to spare on this.

Sorry. Fwiw, there about 70% which is great, and 30% I have concerns with. Maybe PR everything that's refactoring, and open issues for the functional changes where we can discuss each one. In general, we like to avoid:
* input parameters - they add confusion
* Open transparency - think "as a user of the spec" rather than "as the developer of the spec"
* Undetermined form - a feature can be great, but if we can't figure out how to display it perfectly then, it will be a struggle for users to not have unnecessary cognito overhead

Instead optimize for:
* sane default
* usability over features
* clarity over transparency

2024-05-31 16:41 UTC, wparad commented
Closing in favor of smaller PRs. Looking forward to them.

2024-05-31 16:41 UTC, closed without merging